version: '3'

services:
  registry:
    image: registry:2
    restart: always
    ports:
    - "6000:5000"
    # - "443:443"
    environment:
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      #REGISTRY_HTTP_ADDR: 0.0.0.0:443
    volumes:
      #- ./auth:/auth
      - ./data:/data
      - ./certs:/certs
